### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ossamamehmood**
### Add **Security Policy** in README..

_From SECURITY .(MD) file #8_ 

_(Supported and Un-Supported Versions) in README .(MD) file_

### CODE REVIEW

**Review by ossamamehmood — COMMENTED** [review]
### Add **Security Policy** in README..

_From SECURITY .(MD) file #8_ 

_(Supported and Un-Supported Versions) in README .(MD) file_

**Comment by ossamamehmood** [comment]
_I made that shorter (Supported Versions) and removed unsupported in addition add up the follow-up **Release** to **redirect** to **SECURITY. (MD)**_

**Comment by nmanumr** [comment]
You know what, I'm just thinking why we need it? Actually, the project is in a maintenance mood, or maybe not even that. a new version is only released when there is a bug. So actually we don't provide support to any specific version. So I think we don't need it.

**Comment by nmanumr** [comment]
BTW If you won't really want to contribute here are the few things that I would love to have contributions on:
 - Debug and fix the GitHub action to create a release that was weirdly not including some files in the manifest file.
 - Some people reported that the manifest.json file was not picked up properly by chrome on Windows, which could be the encoding issue.
 - Add a popup screen that shows settings when clicked on the extension icon and one the those settings could be to allow auto mark and submit.

Or if you really interested in the project and wants to do something extra there are some ideas from Haris himself that I can share If you are interested.

**Pull request closed without merging**
