### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by ossamamehmood**
### **Sponsor Your Project**

> Create FUNDING.yml

### CODE REVIEW

**Comment by nmanumr** [comment]
This would be great and an incentive for me to maintain this project. But, I'm not sure if this project can lure some funding. But, I would love to hear your opinion on this.

Also, if you are interested would you like to be a co-maintainer of this project?

PS: I really appreciate the research you did to find my Kofi and Patreon pages.

**Comment by ossamamehmood** [comment]
Absolutely 💯 I'm interested in quizsliver app that's why upvote with new stuff to improve the repository.

Pleasure to be the co-maintainer 💫

**Comment by nmanumr** [comment]
Congratulations 🎉 now you have full write permissions on this repository. Also let me know if you are free today I would like to have an online meeting with you.

**Comment by ossamamehmood** [comment]
TYSM 🎊😊, Yeah sure Whenever you available we'll able to meet via Google Meet : )

**Pull request closed without merging**
